[bot]
discord_token = "<DISCORD_BOT_TOKEN>"
client_id = 123456789012345678
owner_id = 123456789012345678
test_guild_id = 123456789012345678

[ai]
gemini_api_key = "<GEMINI_API_KEY>"
advice_instruction = "<ADVICE_COMMAND_INSTRUCTION>"
message_event_instruction = "<MESSAGE_EVENT_INSTRUCTION>"
allowed_guilds = [123456789012345678]